### ISSUE TITLE
colordoppler preview with batch_size > 460

### ISSUE THREAD

**Issue by LucasBenhaim** [DigitalHolography/HoloDoppler#3]
colordoppler preview with batch_size > 460 will crash.

Error msg : 

Error using gpuArray.zeros
Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)'.

**Comment by micatlan** [comment]
case resolved by overriding GPU for preview and do FH & H compute with CPU when the expected size of FH is > to 0.7 x available GPU memory.
